### ISSUE TITLE
It seems that the total number of videos(16129) in "*_CS.txt"(train, test, validation) exceeds the values (16115) described in the paper

### ISSUE THREAD

**Issue by wangwen39** [srijandas07/i3d_smarthome#1]
The extra videos are with class of "Pour.Fromcup", but we didn't get these videos on the provided download link of Toyota dataset.
Can you check this issue?

**Comment by srijandas07** [comment]
@wangwen39 thats an error. We have removed Pour.Fromcup from the list of 31 actions, so you can ignore that class.
Here is the list of 31 actions - 
label =['walk','readbook','Makecoffee.pourwater','Drink.fromcup','Eat.attable','Leave', 'Getup','Sitdown','Cook.stir','Usetelephone','Enter','Cook.Usestove','Watchtv','Cook.cleanup','Drinkfrombottle','Cook.cut','Cook.cleandishes','Uselaptop','Takepills','Drinkfromcan','Eatsnacks','Pour.Frombottle','Pour.fromkettle','Drink.fromglass','Laydown','Maketea.Boilwater','Makecoffee.Pourgrains','Pour.Fromcan','Cutbread', 'Maketea.Insertteabag','Usetablet']
